# Generated by Django 5.2.8 on 2025-11-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=50)),
                ('last_name', models.CharField(db_column='LastName', max_length=50)),
                ('email_address', models.CharField(blank=True, db_column='EmailAddress', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=25, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.AutoField(db_column='ProductCategoryID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'ProductCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('sales_order_detail_id', models.AutoField(db_column='SalesOrderDetailID', primary_key=True, serialize=False)),
                ('order_qty', models.SmallIntegerField(db_column='OrderQty')),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=19)),
                ('unit_price_discount', models.DecimalField(db_column='UnitPriceDiscount', decimal_places=4, max_digits=19)),
                ('line_total', models.DecimalField(db_column='LineTotal', decimal_places=6, max_digits=38)),
            ],
            options={
                'db_table': 'SalesOrderDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderHeader',
            fields=[
                ('sales_order_id', models.AutoField(db_column='SalesOrderID', primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(db_column='OrderDate')),
                ('due_date', models.DateTimeField(db_column='DueDate')),
                ('ship_date', models.DateTimeField(blank=True, db_column='ShipDate', null=True)),
                ('status', models.SmallIntegerField(db_column='Status')),
                ('sales_order_number', models.CharField(db_column='SalesOrderNumber', max_length=25)),
                ('sub_total', models.DecimalField(db_column='SubTotal', decimal_places=4, max_digits=19)),
                ('tax_amt', models.DecimalField(db_column='TaxAmt', decimal_places=4, max_digits=19)),
                ('freight', models.DecimalField(db_column='Freight', decimal_places=4, max_digits=19)),
                ('total_due', models.DecimalField(db_column='TotalDue', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'SalesOrderHeader',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'managed': False},
        ),
    ]
