# Generated by Django 5.2.8 on 2025-11-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_productcategory_salesorderdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(db_column='CartID', primary_key=True, serialize=False)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cartitemid', models.AutoField(db_column='CartItemID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('unitprice', models.DecimalField(db_column='UnitPrice', decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(blank=True, db_column='Subtotal', decimal_places=2, max_digits=21, null=True)),
                ('dateadded', models.DateTimeField(blank=True, db_column='DateAdded', null=True)),
                ('dateupdated', models.DateTimeField(blank=True, db_column='DateUpdated', null=True)),
            ],
            options={
                'db_table': 'CartItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAdress',
            fields=[
                ('addressid', models.IntegerField(db_column='AddressID', primary_key=True, serialize=False)),
                ('addressline1', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AddressLine1', max_length=60)),
                ('city', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=30)),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
                ('postalcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PostalCode', max_length=15)),
                ('spatiallocation', models.TextField(blank=True, db_column='SpatialLocation', null=True)),
            ],
            options={
                'db_table': 'CustomerAdress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerEmailAddress',
            fields=[
                ('emailaddress', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EmailAddress', max_length=50, null=True)),
                ('emailaddressid', models.IntegerField(db_column='EmailAddressID', primary_key=True, serialize=False)),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
            ],
            options={
                'db_table': 'CustomerEmailAddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPassword',
            fields=[
                ('passwordsalt', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PasswordSalt', max_length=10, primary_key=True, serialize=False)),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
            ],
            options={
                'db_table': 'CustomerPassWord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('pk', models.CompositePrimaryKey('customerid', 'phonenumber', 'phonenumbertypeid', blank=True, editable=False, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhoneNumber', max_length=25)),
                ('phonenumbertypeid', models.IntegerField(db_column='PhoneNumberTypeID')),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
            ],
            options={
                'db_table': 'CustomerPhone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('businessentityid', models.IntegerField(db_column='BusinessEntityID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FullName', max_length=101)),
                ('birthdate', models.DateField(db_column='BirthDate')),
                ('groupname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GroupName', max_length=50)),
                ('departmentname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DepartmentName', max_length=50)),
                ('startdate', models.DateField(db_column='StartDate')),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('passwordsalt', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PasswordSalt', max_length=10)),
                ('phonenumber', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhoneNumber', max_length=25)),
                ('emailaddress', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EmailAddress', max_length=50, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.SmallAutoField(db_column='LocationID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=50)),
                ('availability', models.IntegerField(blank=True, db_column='Availability', null=True)),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
            ],
            options={
                'db_table': 'Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCostHistory',
            fields=[
                ('pk', models.CompositePrimaryKey('productid', 'startdate', blank=True, editable=False, primary_key=True, serialize=False)),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(blank=True, db_column='EndDate', null=True)),
                ('standardcost', models.DecimalField(db_column='StandardCost', decimal_places=4, max_digits=19)),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
            ],
            options={
                'db_table': 'ProductCostHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('productdescriptionid', models.AutoField(db_column='ProductDescriptionID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=400)),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
            ],
            options={
                'db_table': 'ProductDescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productinventory',
            fields=[
                ('pk', models.CompositePrimaryKey('productid', 'locationid', blank=True, editable=False, primary_key=True, serialize=False)),
                ('shelf', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Shelf', max_length=10)),
                ('bin', models.SmallIntegerField(db_column='Bin')),
                ('quantity', models.SmallIntegerField(db_column='Quantity')),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
            ],
            options={
                'db_table': 'ProductInventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('productreviewid', models.AutoField(db_column='ProductReviewID', primary_key=True, serialize=False)),
                ('reviewername', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ReviewerName', max_length=50)),
                ('reviewdate', models.DateTimeField(db_column='ReviewDate')),
                ('emailaddress', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EmailAddress', max_length=50)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('comments', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Comments', max_length=3850, null=True)),
                ('modifieddate', models.DateTimeField(db_column='ModifiedDate')),
            ],
            options={
                'db_table': 'ProductReview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankCustomer',
            fields=[
                ('customerid', models.OneToOneField(db_column='CustomerID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='store.customer')),
                ('r', models.IntegerField(blank=True, db_column='R', null=True)),
                ('f', models.DecimalField(blank=True, db_column='F', decimal_places=3, max_digits=5, null=True)),
                ('m', models.DecimalField(blank=True, db_column='M', decimal_places=4, max_digits=19, null=True)),
                ('final_score', models.DecimalField(blank=True, db_column='Final_score', decimal_places=2, max_digits=15, null=True)),
                ('rank_cus', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RankCustomer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysDiagrams',
            fields=[
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productsubcategory',
            table='ProductSubcategory',
        ),
    ]
