# Generated by Django 5.2.7 on 2025-11-19 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_number', models.CharField(max_length=25, unique=True)),
                ('finished_goods_flag', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('safety_stock_level', models.SmallIntegerField(default=0)),
                ('reorder_point', models.SmallIntegerField(default=0)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('list_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_to_manufacture', models.IntegerField(default=0)),
                ('product_line', models.CharField(blank=True, max_length=50, null=True)),
                ('product_class', models.CharField(blank=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('sell_start_date', models.DateTimeField()),
                ('sell_end_date', models.DateTimeField(blank=True, null=True)),
                ('rowguid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productsubcategory')),
            ],
        ),
    ]
